### ISSUE TITLE
React-native.config.js throws error

### ISSUE THREAD

**Issue by Abratemmy** [darshanpawar101/Coffee-Shop-App#3]
Hi Codex, thank you for sharing your video and github link. I am a beginner in react-native, I would appreciate if you can render any assistance.

I created react-native.config.js file as you did in your tutorial but am getting error as seen in the screenshots
![image](https://github.com/darshanpawar101/Coffee-Shop-App/assets/55832177/e9fe2a79-eb49-4275-aff4-8c2d2821bbc0)
![image](https://github.com/darshanpawar101/Coffee-Shop-App/assets/55832177/bffff568-9823-48e3-ae5a-d00f0c11fb06)

Thank you once again, I will be waiting for your  response

**Comment by darshanpawar101** [comment]
Can you Please post the error code and message from the metro server terminal, and try to rebuild the project.
To Rebuild - 
first uninstall any recent libraries you installed by using - npm uninstall <package_name>
cmd1 - cd android
cmd2 - ./gradlew clean
cmd3 - cd ..
cmd4 - reinstall the libraries. 
cmd4 - npx react-native run-android

**Comment by Abratemmy** [comment]
Thanks for your prompt response.

I reinstall node module and is working fine
